name: hive
description: Lightweight and blazing fast key-value database written in pure Dart. Strongly encrypted using AES-256.
version: 2.0.3
homepage: https://github.com/hivedb/hive/tree/master/hive
documentation: https://docs.hivedb.dev/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0
  crypto: ^3.0.0

dev_dependencies:
  test: ^1.15.7

  build_runner: ^2.4.12
  lints: any
  mockito: ^5.4.4
  path: ^1.7.0
  pointycastle: ^3.9.1
